### ISSUE TITLE
Facebook login - Displyed name

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#111]
Backend should return the username of fb user if he logged in before, 
so that users who changed their profile names can see the last edited name not the fb name.

Ex: Backend now return the username as username = fb10153534304230804;
username should be the last edited username stored in backend database

**Comment by avishaan** [comment]
@footnote @ShadiFares 
Today was spent test for this bug but it was not seen. Can you confirm the steps to reproduce. We did the following.
1. Login via facebook
2. Change the username
3. Login via facebook
4. Check that the username is the same as in 2.

Are there different steps that should be followed in order to confirm whether or not this is the case?

**Comment by footnote** [comment]
can't replicate either. must have been reported before the app secret or app id was updated
