### ISSUE TITLE
Need to implement pagination

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#63]
Need to implement pagination in the following routes

1- GET /v1/posts
2- GET /v1/users/{userId}/posts
3- GET /v1/posts/{postId}/comments

**Comment by footnote** [comment]
And this route as well

4- GET /v1/posts/{postId}/users

**Comment by codeHatcher** [comment]
makes sense, we will add a url query parameter called "page" to address this.

**Comment by footnote** [comment]
How much indices returned in a single page?
I posted up to 31 item and they are all returned in page1

**Comment by codeHatcher** [comment]
Depending on the route between 25 and 50.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Wed, Jul 8, 2015 at 8:53 PM, footnote.consulting <notifications@github.com>
wrote:
How much indices returned in a single page?
I posted up to 31 item and they are all returned in page1

—
Reply to this email directly or view it on GitHub
[https://github.com/codeHatcher/lightTribe/issues/63#issuecomment-119772834] .[https://github.com/notifications/beacon/AFHNVmZCIGPy2kO-JQW3rBFfhGhbavBjks5obb2KgaJpZM4FSXcy.gif]

**Comment by footnote** [comment]
We recommend to send a boolean isNext in the response body as used in YouTube APIs to validate if there is an upcoming page or not.

**Comment by codeHatcher** [comment]
We can consider that.
My understanding is normally that is done on Facebook and YouTube when there is
a lot of new data coming in to prevent duplicates. At which point I believe we
would need you to send a query date as well otherwise we couldn't consistently
provide you with an isNext attribute. We would just have you send in the UTC
time and expect you use the same one with each updated request until the user
leaves the view and enters it again.
Let me know if this is something we should explore.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Wed, Jul 8, 2015 at 8:57 PM, footnote.consulting <notifications@github.com>
wrote:
We recommend to send a boolean isNext in the response body as used in YouTube
APIs to validate if there is an upcoming page or not.

—
Reply to this email directly or view it on GitHub
[https://github.com/codeHatcher/lightTribe/issues/63#issuecomment-119773484] .[https://github.com/notifications/beacon/AFHNVu59Qk701VuWQFTWJrq7KUIo-Vk-ks5obb6BgaJpZM4FSXcy.gif]

**Comment by footnote** [comment]
No need to do all of what you have mentioned, it can be done by counting the remaining items and determine if we have an upcoming page or not.

**Comment by codeHatcher** [comment]
Can you give me a link to what you are describing (in regards to isNext with pagination without a cursor)? I am having trouble finding an example of it.

Here is a link of something similar to what we were talking about. Instead of using time they are using the previous objectID or another unique field. https://dev.twitter.com/overview/api/cursoring
